# Generated by Django 3.2.8 on 2024-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
